spring.application.name=dsav

spring.datasource.url=jdbc:postgresql://localhost:5432/dsav
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

jwt.secret=9f2c7e4b1a8d3f6e0c5b9a2d7f1e4c8b6a3d9f2e5c7b1a4d8f6e3c9b2a7d5f1e
jwt.expiration-ms=86400000

glot.api.url=https://glot.io/api
glot.api.token=0b667046-8af2-47e7-844f-9685240f1ca0
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=${GROQ_API_KEY}